### ISSUE TITLE
[Task] Base Textures

### ISSUE THREAD

**Issue by nbrugger-tgm** [FactoryRally/game-client#1]
## Base Textures
Creating textures for all tiles and entities.
Detailed information about the tiles and entities is found `game-controller/documentation`
#### Rules
- Only create static textures (no animations)
- Make textures 3D usable
#### Tasks
- [x] Provide Tiles as a tileset
- [x] Provide Depth-Maps (for all textures
- [x] Provide all textures for a robot in a tileset

**Comment by ComSubVie** [comment]
Why not use the tiles from https://github.com/ShVerni/RoboRuckus/tree/master/Board%20Assets for the first board prototype (released under GPL 3.0) and replace them later with self-made tiles?

**Comment by nbrugger-tgm** [comment]
Seems like a nice temporary solution.
The task is at the moment not bound to a specific timeframe. It is more a task we will do in some point in the project.

**Comment by nbrugger-tgm** [comment]
As this seems to be done i close the issue and add the regarding marks
