### ISSUE TITLE
[Feature] Mocking Server

### ISSUE THREAD

**Issue by nbrugger-tgm** [FactoryRally/game-client#5]
##  Mock Server
**Dependent to : ** https://github.com/FactoryRally/game-controller/issues/8
Create a mock server which serves a static or random game
#### Rules
- Compatible with OAS 3.1 (or 3.0)
- the client needs to be able to handle the data (means it needs to make at least a bit of sense)
#### Tasks
- [ ] Find a tool/software
- [ ] Setup the server
- [ ] Test/validate output/usability

**Comment by nbrugger-tgm** [comment]
### Sources
A source for free OAS software is found here: https://openapi.tools#mock

**Comment by nbrugger-tgm** [comment]
## Deprecated

Since the progress of the game controller is pretty good a Mocking server is not needed anymore
